name: Deploy website

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v6
            - name: Cache dependencies
              uses: actions/cache@v5
              with:
                  path: ~/.npm
                  key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
              working-directory: 04-job-artifacts-and-outputs
            - name: Lint code
              run: npm run lint
              working-directory: 04-job-artifacts-and-outputs
            - name: Test code
              run: npm run test
              working-directory: 04-job-artifacts-and-outputs
    build:
        needs: test
        runs-on: ubuntu-latest
        outputs:
            script-filename: ${{ steps.publish.outputs.script-filename }}
        steps:
            - name: Get code
              uses: actions/checkout@v6
            - name: Cache dependencies
              uses: actions/cache@v5
              with:
                  path: ~/.npm
                  key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
              working-directory: 04-job-artifacts-and-outputs
            - name: Build website
              run: npm run build
              working-directory: 04-job-artifacts-and-outputs
            - name: Publish JS filename
              id: publish
              run: find dist/assets/*.js -type f -execdir echo 'script-filename={}' >> $GITHUB_OUTPUT ';'
              working-directory: 04-job-artifacts-and-outputs
            - name: Upload build artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: dist-files
                  path: |
                      04-job-artifacts-and-outputs/dist
                      # 04-job-artifacts-and-outputs/dist
                      # 04-job-artifacts-and-outputs/package.json
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist-files
            - name: Output filename
              run: echo "${{ needs.build.outputs.script-filename }}"
            - name: Deploy
              run: echo "Deploying..."
